# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: kafka-messaging-service

  profiles:
      active: dev
    
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled:  false

server:
  port: 8085