
# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: notification-service

  profiles:
      active: dev
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled:  false

server:
  port: 8083
  
info:
  applicationName: Metallica Notification Service
  author: Ram Prajapati
  version: 1.0.0
  description: Generates feed for price fluctuations in Commodities Price
  