# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client: #Not a client
    registerWithEureka: true
    fetchRegistry: true

# HTTP (Tomcat) port
server:
  port: 8761   

# profile
spring:
  profiles:
    active: dev
  application:
    name: Trade-Discovery-Microservice

#Managing the logging
logging:
  level:
    com:
      netflix:
        eureka: ON
        discovery: ON

info:
  applicationName: Metallica Trade Discovery Service
  author: Ram Prajapati
  version: 1.0.0
  description: Discovery Service for Registry