# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: trade-service

  profiles:
      active: dev
#Local MongoDB config
  data:
    mongodb:
      host: localhost
      port: 27017
      database: metallica
      
      



# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled:  false

server:
  port: 8081
  
info:
  applicationName: Trade Data Service
  author: Ram Prajapati
  version: 1.0.0
  description: Generates feed for Trade data in Commodities Price
