spring:
  application:
    name: API-Gateway
  profiles:
    active: dev
zuul:
  prefix: /api
  routes:
    refdata-service:
      path: /refdata/**
      serviceId: REFDATA-SERVICE
    marketdata-service:
      path: /marketdata/**
      serviceId: MARKETDATA-SERVICE
    notification-service:
      path: /notification/**
      serviceId: NOTIFICATION-SERVICE
    trade-service:
      path: /trade/**
      serviceId: TRADE-SERVICE
    kafka-messaging-service:
      path: /message/**
      serviceId: KAFKA-MESSAGING-SERVICE

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 246000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 246000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
server:
  port: 8079
  
info:
  applicationName: Metallica NetFlix Zuul Service
  author: Ram Prajapati
  version: 1.0.0
  description: Zuul Service for client expose